project:
  type: website

website:
  title: "Stablecoin Tracker"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: news.qmd
        text: News
    right:
      - icon: github
        href: https://github.com/partrita/stablecoin-tracker

format:
  html:
    theme: cosmo
    toc: true
